### ISSUE TITLE
Unable to init server: Could not connect: Connection refused

### ISSUE THREAD

**Issue by nramani611** [bowang-lab/BIONIC#34]
I have successfully installed Bionic, but when I try to run bionic --help, I get the error in the subject title. The full error is in the file attached.
![Screenshot from 2022-07-11 10-34-00](https://user-images.githubusercontent.com/43153496/178289170-a22e9ebb-8d93-473c-af4a-23549dd8b564.png)

**Comment by duncster94** [comment]
Hi, thanks for opening an issue.

The GDK error has something to do with `matplotlib`, see [here](https://stackoverflow.com/questions/63894814/gdk-critical-103328-827-gdk-cursor-new-for-display-assertion-gdk-is-dis), [here](https://stackoverflow.com/questions/65293542/how-to-resolve-gdk-critical-171303-280-gdk-cursor-new-for-display-assert) and [here](https://stackoverflow.com/questions/13686789/matplotlib-gtk-issue), though looks unrelated to the issue.

The `OSError: libsha-runtime64.so.1` error looks like something to do with RadeonOpenCompute, see [here](https://github.com/RadeonOpenCompute/ROCm/issues/1721).

Can you answer a few questions for me? 
What operating system are you running? Did you install via wheel or using poetry? If you installed by wheel, which wheel file did you use? Do you already have CUDA installed on your system? Are you using a GPU? If so, what model?

**Comment by nramani611** [comment]
I am using Ubuntu Version 20.04.4. I installed bionic with the given command where OS = linux_x86_64, VERSION = 0.2.4, and CUDA = cu111 via wheel. I do have CUDA installed on my system and am using an NVIDIA 3070 TI.

**Comment by duncster94** [comment]
Can you run `echo $PATH` and copy/paste the output?

**Comment by nramani611** [comment]
This is the output:

/home/nramani/.local/bin:/home/nramani/anaconda3/envs/bionic/bin:/home/nramani/anaconda3/condabin:/usr/local/cuda-11.6/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

**Comment by duncster94** [comment]
Hmm, I'm not sure why you're getting that error. There are a few ways to debug however:

1. Since it could be CUDA related, one thing you can try is installing the [CPU only wheel](https://github.com/bowang-lab/BIONIC/releases/download/v0.2.4/bionic_model-0.2.4+cpu-cp38-cp38-linux_x86_64.whl) and see if that solves the problem. If that works then we know it's a CUDA issue and we can go from there.
2. Another thing you can try is the [installation via Poetry](https://github.com/bowang-lab/BIONIC#installing-using-poetry-recommended-for-development). This way you will have more control over the install process so if a dependency is missing you can add it easily.

I'd recommend you try option 1. first and if that fails move on to option 2.

**Comment by nramani611** [comment]
I tried your first solution and got the same error. The screenshot is attached here. I will try the second solution and let you know how it goes.
![image](https://user-images.githubusercontent.com/43153496/178380311-0d54a608-c3d7-4b7f-b54e-994e8882a44c.png)

**Comment by duncster94** [comment]
Hi, I think this is an issue with the `LD_LIBRARY_PATH` system variable, see point 1 under the PyTorch Geometric [FAQs](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#id1). Try setting `LD_LIBRARY_PATH` as in [this](https://github.com/pyg-team/pytorch_geometric/issues/2040#issuecomment-766610625) response and let me know if that fixes your issue.

**Comment by nramani611** [comment]
I think I have somewhat resolved the issue. I think I had missing packages and through the links you sent, I was able to install them. The error message has changed now as shown in the screenshot.
![image](https://user-images.githubusercontent.com/43153496/178525541-03bcd0fd-cb39-490f-a631-7555bada4829.png)

**Comment by duncster94** [comment]
Can you elaborate on what packages were missing?

JAX is not part of the installation, so I'm not sure where that error is coming from. Are you able to run BIONIC successfully? You can try running the config from [here](https://github.com/bowang-lab/BIONIC/blob/master/bionic/config/yeast_gi_coex_ppi.json) using the networks from [here](https://github.com/bowang-lab/BIONIC/tree/master/bionic/inputs).

**Comment by nramani611** [comment]
Bionic seems to be working with the sample files you provided. The package I installed was the rocm-dkms package. However, I still get the JAX error whenever I run Bionic.

**Comment by duncster94** [comment]
Thanks for the information. The JAX problem looks unrelated to BIONIC since it's not a dependency. It's a warning rather than an error anyway, so it can probably be ignored. Either way, it shouldn't impact BIONIC.

I'm going to close this issue but if you run into other problems feel free to reopen it and I'll help you out.
