### ISSUE TITLE
TypeError: 'PosixPath' object is not iterable

### ISSUE THREAD

**Issue by nramani611** [bowang-lab/BIONIC#35]
I'm trying to input a label_names json file. The format of the file is the same as the example provided [here](https://github.com/bowang-lab/BIONIC/blob/master/bionic/inputs/yeast_IntAct_complex_labels.json). However, when I run bionic I get the following error: 
![image](https://user-images.githubusercontent.com/43153496/182411926-d66f477b-f61b-4be0-971a-d67bdff383ae.png)

**Comment by duncster94** [comment]
Hi, thanks for opening an issue. Can you copy/paste your config file?

You should double check the `label_names` value in the config is a list containing the path to your label file (since you can specify multiple label files) and not just the path itself (see how `label_names` is a list [here](https://github.com/bowang-lab/BIONIC/blob/master/bionic/config/yeast_gi_coex_ppi_semisupervised.json)).

Let me know if that helps!

**Comment by nramani611** [comment]
I fixed the issue, as I realized that the label_names needs to be a list. Thanks for your help.
